### ISSUE TITLE
Manage secrets

### ISSUE THREAD

**Issue by azawadzka** [azawadzka/TravellerChatbot#4]
Manage OPENAI_API_KEY env in docker container and locally

**Comment by azawadzka** [comment]
Bumped Python version from 3.10.14 to 3.11.9 because `StrEnum` wasn't available. Otherwise also good idea to bump.

**Comment by azawadzka** [comment]
Mind the difference between build secrets and service secrets
build secrets:
```
services:
  server:
    build:
      context: .
      secrets:
        - OPENAI_API_KEY
```
service runtime secrets:
```
services:
  server:
    build:
      context: .
    secrets:
      - OPENAI_API_KEY
```
